### ISSUE TITLE
Reddit karma not work

### ISSUE THREAD

**Issue by auxten** [fiplab/Infinity-Dashboard-Modules#12]
**Module Name**
Reddit karma

**Describe the bug**
just not work

**Steps To Reproduce**
run it

**Expected behavior**
show karma

**Screenshots**
```
22/04/2019, 09:40:29 - Result Failed - Error: navigation error
22/04/2019, 09:41:04 - Result Failed - Invalid response while processing
```

**Desktop (please complete the following information):**
 - OS: 10.12.6
 - Infinity Dashboard version: I don't know how to get it, should be latest

**Additional context**
my Reddit id is "auxten"

**Comment by emilylaguna** [comment]
Hi, this has been fixed in the latest Infinity Dashboard release.
